server:
  port: 8080
spring:
  application:
    name: app
logging:
  level:
    '*': DEBUG
---
logging:
  level:
      '*': INFO
server:
  port: 8443
spring:
  config:
    activate:
      on-profile: production